services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/acme.json:/acme.json
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.kndbvortex.cloud`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      

  website:
    image: nginx:alpine
    restart: always
    container_name: portfolio
    volumes:
      - ./website:/usr/share/nginx/html
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`kndbvortex.cloud`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls.certresolver=letsencrypt"
      # Redirect HTTP to HTTPS
      - "traefik.http.routers.website-http.rule=Host(`kndbvortex.cloud`)"
      - "traefik.http.routers.website-http.entrypoints=web"
      - "traefik.http.routers.website-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  web:
    external: true
