name: Automate deployment on VPS
on:
  push:
    branches:
      - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Execute remote SSH commands using password
              uses: appleboy/ssh-action@v1
              with:
               - host: ${{ secrets.HOST }}
               - username: ${{ secrets.USERNAME }}
               - password: ${{ secrets.PASSWORD }}
               - port: ${{ secrets.PORT }}
               - script:
                  whoami
                  cd cd app/portfolio/
                  git pull origin master
                  docker-compose up website --build -d